### ISSUE TITLE
Keychain is not cleaned up

### ISSUE THREAD

**Issue by savage7** [openbakery/gradle-xcodePlugin#133]
Version: 0.10.1

When building the keychain isn't clean up after the build. The generated "gradle-xxxx" isn't removed from the keychain as keychainClean isn't called as kind auf cleanup. 

Is this on purpose? I would expect that every tasks cleans up itself after it finishes.

It built iOS Example Project with gradle appstore, these build tasks are executed:
:xcodebuildConfig
:infoplistModify
:keychainClean
:keychainCreate
:provisioningClean
:provisioningInstall
:xcodebuild
Done
:archive

**Comment by renep** [comment]
The keychain is cleaned up when the keychain file itself does not exist anymore. So after the build the keychain remains, which is (in my opinion) not a big problem, because when building with gradle it is always the own keychain appended als parameters to xcodebuild or codesign.

You will only run into problems when you run the build on the local machine, and than what to build with Xcode. With Xcode all keychains are searched for the proper certiticate and the first found is taken.

Same for provisioning profiles, they are also not removed as long as the physical file in the build directory exists.

**Comment by savage7** [comment]
Ok it a good point it's removed when the keychain file is deleted.
What happens on our build server:
We have for example 15 different builds which all are signed with our enterprise certificate.
After the builds finishes the gradle build chain isn't removed. In the worst case there are 15 gradle temp keychain there, all with the same enterprise signing id.
I'm not really sure if there is a connection but we get the password needed for keychain dialog very often. Which regularly breaks our builds. If I remove all the gradle keychains it works again.

**Comment by renep** [comment]
Normally you should not get a password dialog on the gradle build if everything is correct configured, in the build.gradle file. 
I have checked on my build server and I have 10 gradle keychains with only 3 different certificates. I do not have password popups.

The xcodebuild itself does a signing, and I would guess that you have a problem there. You can check the build/xcodebuild-output.txt and see what identity and keychain is used, and if this matches with the cert in the keychain.
If not, the xcodebuild searches all keychains for a matching certificate, and there you get the password prompt.

I think if this is really a bug in the plugin, than this one will be a difficult one to find.
What you can to if you do is that you execute a 'gradle keychainClean' after every successful build. Then only the keychain should be cleaned, but not the other build output.

**Comment by renep** [comment]
This issue is obsolete now with release 0.11.2. In this released I have changed that the keychain is removed from the search list after the xcodebuild. Therfore the gradle keychains should not be in the search list anymore after the build.
