### ISSUE TITLE
how can i use apple testflight?^_^

### ISSUE THREAD

**Issue by philZH** [openbakery/gradle-xcodePlugin#151]
> Could not find method testflight() for arguments [build_dqh654b17dm584setqhovykug$_run_closure2@13e5d243] on root project

**Comment by renep** [comment]
There are two parameters that you have to set in your build.gradle file or via -P parameter: 
`applestore.username` - This is your apple Id
and 
`appstore.password`- this is your password

There are two task you can run: `appstoreValidate` and `appstoreUpload`. The first only verifies that create ipa is accepted by itunes connect, the second also uploads it.

You need to run the `package` task first, so that the ipa is created


-P Parameter: run gradle with `gradle appstoreValidate -Papplestore.username=<myAppleId> -PapplePassword=myPass`

**Comment by philZH** [comment]
thank you, can you give me an example?

**Comment by renep** [comment]
just add

```
appstore.username = your_apple_id
appstore.password = _your_apple_id_password
```

to your build.grade file
