### ISSUE TITLE
Cocoapods tasks ignores Podfile updates

### ISSUE THREAD

**Issue by emartynov** [openbakery/gradle-xcodePlugin#199]
It would be great if cocoapods would analyze dependencies changes

**Comment by renep** [comment]
It should do this since version 10.3. Here the Podfile.lock and the Manifest.lock are compared, and If they are not equals, that a 'pod install' is run.

**Comment by emartynov** [comment]
Rene, try to modify Podfile and try to run `cocoapods` task. Nothing happens

**Comment by renep** [comment]
Ok...
My workflow so far is that when I change the Podfile, I run an 'pod update' manually. My idea is that the Podfile.lock is the key file and it should be used as long as I do not run 'pod update'. I don't know what was the design decision for cocoapods was why 'pod install' also installs new versions if the Podfile was changed. (I would not have done that)

I do not what to run 'pod install' on every build, because in most of the cases it is not necessary and slows down the build.
Therefor the solution would be to parse the Podfile and Podfile.lock and run 'pod install' when the dependencies have change.

Workaround for now: delete the Podfile.lock

**Comment by emartynov** [comment]
We also keep pods together with project. I would not run pod install on every build as well.

Thank you for clarification and nice plugin

**Comment by renep** [comment]
On thing that also always runs 'pod install' is when you execute gradle with the parameter '--refresh-dependencies'

**Comment by emartynov** [comment]
We also discovered it yesterday. But it also update the plugin itself and other dependencies.

**Comment by adil-hussain-84** [comment]
Has anything changed with the recent releases of the plugin? Just tried doing a build with the latest version of the plugin (0.12.5) and looks like changes in my project's `Podfile` are not picked up. Is there any task in this plugin that runs the `pod update` command... or is executing Gradle with the '--refresh-dependencies' parameter still the only way to do this?

**Comment by renep** [comment]
@adil-hussain-84 I have created a new Issue for this, because I think this is a good addition: #241

**Comment by adil-hussain-84** [comment]
Awesome. Thanks @renep. Right now I'm having to call `pod update` before calling `gradle build` on my project. Would be great to have the `pod update` happen as part of the build.
