### ISSUE TITLE
Execution failed for task ':xcodebuildConfig' in 0.11.5

### ISSUE THREAD

**Issue by bitcrumb** [openbakery/gradle-xcodePlugin#205]
Hi,

we've suddenly been experiencing the following error on multiple repositories since the 0.11.5 release. (note that the the 0.11.4 release works just fine), the error is as follows:

```
* What went wrong:
Execution failed for task ':xcodebuildConfig'.
> Command failed to run (exit code 1): '/usr/libexec/PlistBuddy /Users/Lode/Development/iOS/Projects/xxx/XXX.xcodeproj/project.pbxproj -c Set :objects:AA53629E8D3108EC548DAA55:buildSettings:PROVISIONING_PROFILE ea5a9fe4-ce59-431d-b499-dc10d447d718'
  Tail of output:
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  <key>AppIDName</key>
  <string>Xcode: Wildcard AppID</string>
  <key>ApplicationIdentifierPrefix</key>
  <array>
  <string>PD26XC64G7</string>
  </array>
```

Any idea on what could be going wrong?

**Comment by renep** [comment]
I think this has to do with the watch kit pull request Issue #185
I have reverted the pull request an the develop-0.11 branch and preparing a test build. My build pipelines is currently running on my go.cd build server, to verify if all tests are working. This takes a few minutes ;-)

**Comment by renep** [comment]
Can you give version 0.11.6-TEST a try.

You need to use:
```
buildscript {
	repositories {
		maven {
			url('http://repository.openbakery.org/')
		}
		mavenCentral()
  }

	dependencies {
	    classpath "org.openbakery:xcode-plugin:0.11.6-TEST"
	}
}
```

**Comment by bitcrumb** [comment]
This indeed fixes the issues! The build script now continues as expected.
Too bad, because we were anxiously awaiting watchkit support as well :) Hopefully you can track down the origin of this bug!

**Comment by renep** [comment]
I have created a 0.11.6 version with this change.

**Comment by renep** [comment]
I had not merged the WatchKit pull request for some time and I also want this in the plugin. Normally I only add stuff that I want or need for my projects.
I have merge this and release a version because the example projects and all unit tests did work well. The problem is that only a few unit test where in the pull request. In the future I will think twice if I merge such requests. My goal is to have a reliable tool for building.

I hope I will find some time to address the WatchKit support, but I cannot make any promises, because the gradle plugin is (mostly) a free time project and I need to do other stuff for a living ;-)

**Comment by bitcrumb** [comment]
I totally understand you René. Your work is very much appreciated and I hope that I might one day be able to contribute as well. Keep it up! :)
