### ISSUE TITLE
Custom codesigning tool 

### ISSUE THREAD

**Issue by BamX** [openbakery/gradle-xcodePlugin#212]
Hi!
In my project I'm using custom codesigning tool. I want this plugin to support this customization. There will be fine if codesign method in PackageTask class is a customizable closure. 
I could make a pull-request if you'll accept it.

**Comment by renep** [comment]
Hi,

I'm wondering what your customization for the codesigning is?
If you have need for additional codesign parameters that make sense then 
feel free to submit a pull request ;-)
I always try to merge pull requests. I have added some collaboration 
infos to the Readme.md that make life easier for me ;-)

Currently I have change some things with codesigning that you will find 
in the develop branch, but it is not finished yet, because the codesign 
is not valid. The change of the codesiging is, that at the package task 
the entitlements are set using the data from the mobile provisioning 
file, but some thing is not right with the entitlement. I will address 
this problem in the next days.

Regards,
René

**Comment by BamX** [comment]
Fine! I'll add customization in pull-request soon.

**Comment by BamX** [comment]
As result of not providing certificate/provisioningProfile package task fails. So could I add option to disable signing? I could disable package task, but it makes useful work in addition to signing.

**Comment by renep** [comment]
I know that disabling the cert and provisioning profile will fail the package task ;-)
My Idea was do modify the package task that if this two are not provided that the package task behaves the same, but skips the codesign.

If you create a pull request for this, then also add an warning that no codesign was performed.

**Comment by BamX** [comment]
Oh, I see. I'll do it today

**Comment by BamX** [comment]
Could I not provide "xcodebuild.signing" at all? I find reference to signing identity in xcodebuild and archive tasks. Is it strongly required in them?

**Comment by renep** [comment]
Have you pull the latest develop branch?

I have removed the signing stuff from the XcodeBuild Task. Only the package has signing now.
