### ISSUE TITLE
Code Signing failure

### ISSUE THREAD

**Issue by eseilnacht** [openbakery/gradle-xcodePlugin#223]
Hello, recently I started receiving this codesign error during our Jenkins builds.  It is not 100% consistent but happening frequently enough to be a real issue.

I had been using 0.10.+  and am also seeing this with 0.11.5.   I tried moving to 0.12.+ but was unable to get signing to work at all with that version.

User interaction is not allowed.
Command /usr/bin/codesign failed with exit code 1

*\* BUILD FAILED **

The following build commands failed:
    CodeSign build/sym/Debug-iphoneos/MBankPhone.app
(1 failure)

Any advice would be appreciated.

**Comment by renep** [comment]
Let me guess. The code signing you are talking about is the codesiging that xcodebuild itself does? Not the code signing at the package task.
If so then this is the problem because xcodebuild should not sign anymore. It is not necessary for the build at compile time therefor I have disabled it by telling xcodebuild not to sign. But xcodebuild tries to sign after all.

I never had this problem myself so I also cannot verify it, but I have chatted with someone who had. His solution was do create the Xcode project again, because something is wrong in the project file. Maybe just create the target again does help.

I would really liked to know what the real problem here is, but because I can not verify this issue myself I can not investigate it.

I do not want to go back to who things are done in the 0.11 version and before, because the solution now I find much better and I hope that this is also an issue that can be sorted out. I would be nice to get some more information here, so that this can be solved either by a change in the plugin or by an entry in the documentation ;-)

**Comment by eseilnacht** [comment]
Turns out the issue had to do with expiration of the temporary keychain created before running xcodebuild.  Apparently the build step intermittently started to take longer that the default timeout ( 5mins ).  Increasing the timeout using the following command seems to have corrected the error.
{code}
security set-keychain-settings -t 3600 path-to-keychain
{code}

**Comment by renep** [comment]
In 0.11 there is already an option to increase this timeout (see timeout parameter at signing). It is still there is 0.12 but not needed anymore, so in one of the future version it will be removed.
Why it is not needed anymore is because the keychain is not created at the beginning of the build anymore. Instead it is created after the compile and before the package task. Only when creating the IPA itself the code signing and keychain is needed, and this task should never take 5 minutes ;-)

**Comment by eseilnacht** [comment]
Hi Rene
What is the preferred way to invoke code signing with 0.12 ?  I tried adding a dependnecy on the archive+package tasks but it was skipping the code signing step because it thought it was not a device build.  This was for release builds too.
Thanks. 


     On Monday, November 16, 2015 10:27 PM, René Pirringer <notifications@github.com> wrote:
   

 In 0.11 there is already an option to increase this timeout (see timeout parameter at signing). It is still there is 0.12 but not needed anymore, so in one of the future version it will be removed.
Why it is not needed anymore is because the keychain is not created at the beginning of the build anymore. Instead it is created after the compile and before the package task. Only when creating the IPA itself the code signing and keychain is needed, and this task should never take 5 minutes ;-)—

**Comment by renep** [comment]
With 0.12 I have removed the sdk value because of watch os support and introduced a type and simulator value. You need to set
```
xcodebuild {
  type = iOS // iOS is the default value, therefor you can skip this value
  simulator = false
}
```
Then a device build is created when you run 'gradle archive package'

**Comment by huangjimmy** [comment]
I encounter this problem too.
If I run gradle xcodebuild in jenkins and this code signing problem occurs.
If I run gradle xcodebuild in terminal then the build process is successful.

Still not sure why this happen.
