### ISSUE TITLE
Archive task build without destination

### ISSUE THREAD

**Issue by phil443** [openbakery/gradle-xcodePlugin#224]
Hi,

I'm trying to generate an *.ipa for Ad Hoc distribution with this gradle plugin but I've run into an odd issue. 

If i understand correctly, to generate the *.ipa, I have to run the 'archive' task and then the 'package' task (correct me if I am wrong as I'm not totally clear on this). Running the 'archive' task results in the following error: "xcodebuild: error: Unable to find a destination matching the provided destination specifier:" 

The actual 'xcodebuild' command shown when it fails appears to be using the the option "-destination platform=iOS Simulator,name=Resizable iPhone,OS=8.1". I just want to perform an archive purely to allow me to generate an *.ipa file with the package task afterward, in which case the destination option seems unnecessary. Does the archive task require the destination option? If not how can i disable this? I've tried adding "simulator = 'false'" to the xcodebuild config but it had no effect.

Here's my Gradle build script:

```groovy

plugins {
    id 'org.openbakery.xcode-plugin' version '0.12.3'
}

xcodebuild {
    scheme = 'Scheme'
    target = 'Target'
    type = 'iOS'
    configuration = 'Release'

    signing {
    	certificateURI = 'file:///filepath/signing_key.p12'
    	certificatePassword = 'password'
    	mobileProvisionURI = 'file:///filepath/xc_ad_hoc.mobileprovision'
    }
}
```

I'm am testing this by executing 'gradle archive' in the top level of the project directory.

Any help is greatly appreciated.

**Comment by renep** [comment]
Yes you need to run 'archive' and 'package' to create an ipa. The 'archive' task create an xcarchive, same as Xcode does when you run build and archive. The package task is the same as the export in the Xcode organizer. It takes the archive and create an ipa.

You need the simulator = false because otherwise a build for the simulator is created, and the '-destination' is only added when performing an simulator build.
Then execute 'grade clean archive package' and this should work.

Otherwise please post the error message here.

Also with archive and package task should work for the simulator (package create here an zip). But in your cause the compile fails because your simulator setup is messed up as it seems. You can fix this by simply calling 'gradle simulatorCreate' and is should delete all simulators and create it again.

**Comment by phil443** [comment]
It turns out when I tried using the simulator setting, I had set the variable to the string 'false', rather than a boolean, so naturally it didn't have any effect. A bit of an oversight on my part. I've rectified this and the the command 'gradle clean archive package' works fine now. Thanks for the response.
