### ISSUE TITLE
Keychain Access Group wildcard

### ISSUE THREAD

**Issue by BamX** [openbakery/gradle-xcodePlugin#226]
It's about keychain-access-groups again.
As I see, xcodePlugin creates entitlements from provisioning profile and doesn't use existing entitlements? If so, why?

The problem is that it's look like wildcard (A1B2C3D4.*) access group and enterprise provisioning profile not allows to write in shared keychain.
It's strange the only difference in two builds (one of them working, other - not) is concrete or wildcard access groups.

**Comment by renep** [comment]
For signing an entitlement is always needed and the best way imho is to fetch it from the provisioning profile. The provisioning profile has the entitlements embeeded, and therfor this is the one used for the appstore and it must match the entitlements from the signing.
As far as I have seen, an entitlements file is created when you switch the keychain sharing on, but it has 
ony the keychain-access-group but no other settings.

Also I have seen that you can set the keychain-access-group in the apple member center when setup the App-Id. So this coult be the option now, so that you have the proper value for now.

A future addtion can also be that when the provisioning profile contains a wildcard entitlements it is merged with the given entitlements, or it can be set in the build.gradle file.

**Comment by yvasileuski** [comment]
We have lots of apps each with specific set of access group values. So it is impossible to create all-in-one profile. And the only suitable way is to merge entitlements.

**Comment by renep** [comment]
I will look into it.

**Comment by BamX** [comment]
Hi! Is there any progress with this issue?

**Comment by renep** [comment]
Yes I'm on it, but not finished yet, but soon I hope ;-)

**Comment by renep** [comment]
I have created a test version 0.12.4-TEST2 that contains the fix and uploaded it to repository.openbakery.org
Please let me know if this works now for you.

**Comment by BamX** [comment]
It's working with AppStore configuration(certificate, provisioning), but with Enterprise provisioning it's still uses wildcard keychain access group.

**Comment by renep** [comment]
I need more information here, because I do not have an enterprise certificate.

With the update a xcent file is created in the archive, that should be the same as the archive xcode creates.
The entitlement for the siging is still extracted from the provisioning profile and the keychain-access-group from the xcent file is merged into the extracted.

Maybe you could mail me a debug output when you run this, so that I can get clou whats wrong.


Can you give me a bit more Information. Can you look into the created archive and see what the content of the xcent file is.

**Comment by BamX** [comment]
I've tried today again. Everything looks good, keychain access groups are correct now. I'll wait for 0.12.4 release. Thank you!

**Comment by BamX** [comment]
I've found one problem. If there is CFBundleIdentifier not set in project build settings getBuildConfiguration from XcodeBuildPluginExtension will not find current BuildConfiguration, but it's not strongly required to be set to build application. Because of this some project's entitlements will not be archived(XcodeBuildArchiveTask.groovy:224) and merged.

**Comment by BamX** [comment]
And one more significant problem. Why are you replacing groups prefixes with team identifier? In my apps, it not equals to actual team identifier. I think it should equal application identifier prefix(like in xcent file).

**Comment by renep** [comment]
I'm wondering if it is a valid case that no CFBundleIdentifier it set?

I have changed now that not the team-identifier is used as prefix, this was a bug, because in my profiles sometimes the team identifier and the prefix are the same, so I missed this. I will provide a new test version when I'm back in my office later today (hopefully ;-) )

**Comment by BamX** [comment]
Well, that's great!
And yes, I've seen projects with no CFBundleIdentifier and it builds and works well.

**Comment by renep** [comment]
I have created a test version 0.12.4-TEST4 now. Please let me know if this version works now as expected.

**Comment by BamX** [comment]
I've just built with this version and it looks like everything works fine. Waiting for release now.
Thank you!

**Comment by BamX** [comment]
Hi! When are you planning to release 0.12.4?

**Comment by renep** [comment]
Release build is running, if everything is fine a new version should be published in a few minutes

**Comment by BamX** [comment]
Thank you!

**Comment by BamX** [comment]
Did something go wrong? There is no 0.12.4 release...
http://repository.openbakery.org/org/openbakery/xcode-plugin/0.12.4/xcode-plugin-0.12.4.pom

**Comment by renep** [comment]
Please try again, ftp upload from the build server did not work, so I
did it manually

Nikolay Volosatov wrote:
>
> Did something go wrong? There is no 0.12.4 release...
> http://repository.openbakery.org/org/openbakery/xcode-plugin/0.12.4/xcode-plugin-0.12.4.pom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openbakery/gradle-xcodePlugin/issues/226#issuecomment-163277771>.
>

-- 
My PGP Key: http://keybase.io/rpirringer
Fingerprint: D00C 9E16 8B15 C90B E4AA  9721 7DCA 1010 CCC0 4794

**Comment by BamX** [comment]
I've found a problem. If CFBundleID is something like $(CUSTOM_BUNDLE_ID) proper build configuration will not be found by getBuildConfiguration function. Could it be fixed somehow?

**Comment by BamX** [comment]
@renep hi there! Could you say something about a problem I described above? Now I have to fill PRODUCT_BUNDLE_IDENTIFIER in all projects that have environment variables in CFBundleID in Info.plist. It could produce significant problems in production(keychain sharing is critically important for my projects). If you have an idea how to fix it I could probably try to make some pull-request.

**Comment by renep** [comment]
I do not use variables for BundleIdentifiers. I'm wondering if it is a good use case to have variables there. I have not thought this through, but I think this could make things very complicated during build.

What I do is, that I set the BundleIdentifiers at the begin of the build to the proper value.
e.g.:
```
project.ext.baseBundleIdentifier= 'com.example.MyApp'

infoplist {
  bundleIdentifier = project.ext.baseBundleIdentifier + '-Test'
}
```

I know that there is a problem here when using extensions, that there is no support for this, but I'm thinking about this and I hope to find a good solution for this.

For now I use a workaround that looks like this:
```
import org.openbakery.util.PlistHelper
import org.openbakery.CommandRunner

task updateInfoPlist() {
	doLast {
		PlistHelper plistHelper = new PlistHelper(project, new CommandRunner())
		plistHelper.setValueForPlist('./MyApp-DocumentProvider/Resource/Info.plist', "CFBundleIdentifier", infoplist.bundleIdentifier + ".DocumentProvider")
		
	}
}
```

And I make the InfoplistModifyTask dependend to the uploadInfoPlist task:
```
infoplistModify.dependsOn updateInfoPlist
```

Therefor I use the power of gradle here ;-)

**Comment by BamX** [comment]
It could be a solution for single project, but I created universal script that can be used for many projects. I've tried to find a way for resolving environment variables in Info.plist but found nothing.

**Comment by renep** [comment]
I do not agree that this is only a solution for a single project. Gradle is a very powerful tool. I don't know what you project setup is, but I'm very confident that this also works with multiple projects.

Do not use variables in Info.plist. Use the power of the gradle build to set the proper values.

**Comment by BamX** [comment]
For the power of Gradle! Thank you, I'll try to work with this. (:
