### ISSUE TITLE
Invalid Swift Support

### ISSUE THREAD

**Issue by BamX** [openbakery/gradle-xcodePlugin#231]
Hi, @renep 

In 0.12.4, you say, "SwiftSupport in not included anymore, because it is not needed".
But after build with 0.12.4 Apple decline build with message:
> Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

**Comment by renep** [comment]
I have received the information of someone who uses this plugin that the resulting binary is bigger then the one xcode creates and he suggested that the SwiftSupport was not present in the ipa xcode creates. Therefore I have removed it. I myself have not tested it.
I'm wondering if I should revert the change, because I do not have time this week to investigate it deeper.

**Comment by BamX** [comment]
I think you should. Or you should provide a flag that disables SwiftSupport providing.

**Comment by mathiasnagler** [comment]
Which version of Xcode are you using and what baseSDK version?

**Comment by BamX** [comment]
Xcode 7.1.1 with "Latest iOS" SDK, on build machines.

**Comment by renep** [comment]
I have reverted the change with 0.12.5
