### ISSUE TITLE
Prompting for Keychain Password even when included

### ISSUE THREAD

**Issue by jeremybarr** [openbakery/gradle-xcodePlugin#251]
When running `gradle archive package` I've specified all the signing parameters as part of the xcodebuild command, including the keychain file and keychain password.  However, when it gets to the package command (I think) it is still prompting for the keychain password. This works fine when running the gradle commands locally, but on a CI server like Jenkins this causes the build to fail every time.  Am I missing something in regards to keychain signing?

**Comment by renep** [comment]
Yes.
Am I right that you have set the keychain with:
```
signing {
   keychain = ....
}
```
Do not specify the keychain, only the `certificateURI`, `certificatePassword` and `mobileProvisionURI`. The build create a keychain that is only used by the build in the package task and in the end the keychain is removed again. The reason is to avoid conflicts.
See also the examples here: 
https://github.com/openbakery/gradle-xcodePlugin/tree/master/example/iOS

**Comment by jeremybarr** [comment]
I have set the keychain that way. I've never tried using the cert specifically.  On first past I then had problems with the signing identity then so I'll have to dig into that as well.  I assume I still need to include the identity parameter correct?

**Comment by renep** [comment]
Yes, you will need the identity.
When you use the `certificateURI` then the identity is automatically set using the value from the certificate.

When you use the `keychain` parameter, than you must make sure that the codesign command line tool has the proper rights to access the keychain. Otherwise you will get a message like 'User interaction not allowed'. This will be your problem in Jenkins.

Because codesigning is not trivial  I strongly recomment NOT using the `keychain` parameter. For a good reason I have introduced the `certificateURI`, `certificatePassword` and `mobileProvisionURI` so that during the build a keychain is created the propery way with the proper access rights.
