### ISSUE TITLE
Cannot setup sdk param for xcodebuild

### ISSUE THREAD

**Issue by rodrigocollavo** [openbakery/gradle-xcodePlugin#254]
Im using 0.13.0 version.
Actually when I run xcodebuild command I cannot setup -sdk param.
My current issue is, my environment starts using iphoneos sdk automatically, but it switches to iphonesimulator when I run xcodebuild again (or after the 3rd try sometimes).
My Xcode project settings is using 'iphoneos', but looks like it ignores this value.
The only way to fix this problem is setting the -sdk param, but this parameter is not available actually. Another solution is using "-project xxx.xcodeproj" instead of "-scheme xxx", this solution doesn't require to specify the -sdk, and it builds for iphoneos correctly.

This is my current gradle configuration:

xcodebuild {
    ...
   type = 'iOS'
   simulator = 'false'
}

**Comment by renep** [comment]
I have removed the sdk parameter for a good reason, and it is not needed anymore. If you have a hybrid app like iOS and tvOS, or iOS and watchOS you need 2 sdks therefor this parameter does not make sence anymore.

That the `iphoneos` setting in the Xcode project is ignored is also correct, because the plugin is is designed this way. Bacause it is overruled by the things you in the build.gradle.

Nevertheless you problem is in the config: 
```
xcodebuild {
  type = 'iOS'
  simulator = false // <- remove the quotes here!!!
}
```

This is a known issue that it does not work when using quotes. This will be fixed in the next version.

**Comment by rodrigocollavo** [comment]
Testing this but still same result. The issue looks to be related to a computer specific config, the problem is happening in one computer only (at least it didn't happen in a different machine).
If this is related to an xcode configuration or terminal environment configuration, we can't find out the problem exactly.
What I can tell is, we restart the computer and works fine, but it switches to iphonesimulator automatically when we run the task 2 or 3 times (same if we run xcodebuild externally using '-scheme ...', so the plugin is not switching the environment, it's something related to xcodebuild/xcode project settings)
Everything goes back to normal after a machine restart.

Actually we have to remove the plugin and create an individual gradle task using "-project xxx.xcodeproj"
