### ISSUE TITLE
"no identity found" on Jenkins

### ISSUE THREAD

**Issue by Dyrkorn** [openbakery/gradle-xcodePlugin#256]
When we run our gradle script on Jenkins, we get "Tail of output: no identity found". After searching the forums we can not find out why our script doesn't work.

Gradle script:

```
xcodebuild {
    def pwd = "pwd".execute().text.trim()

    version = "7"    
    configuration = {configurationName}
    target = {targetName}
    scheme = {schemeName}

    type = 'iOS'
    simulator = false   

    signing{
        mobileProvisionURI = 'file://' + pwd + '/gradle/signing/PM_distribution.mobileprovision'  
        certificateURI = 'file://' + pwd + '/gradle/signing/dist-PM.p12' 
        certificatePassword = '**password**'
    }  
}
```

Jenkins output:

```
:provisioningClean
:provisioningInstall
:cocoapodsInstall
:xcodebuildConfig
:infoplistModify
:xcodebuild
Done
:archive
:keychainClean
:keychainCreate
:package FAILED
:keychainRemove

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package'.
> Command failed to run (exit code 1): '/usr/bin/codesign --force --sign null --verbose /Users/Shared/Jenkins/Home/workspace/{PROJECT_NAME}/build/package/Payload/{APP_NAME}.app/Frameworks/AFNetworking.framework --keychain /Users/Shared/Jenkins/Home/workspace/{PROJECT_NAME}/build/codesign/gradle-1459858870792.keychain'
  Tail of output:
  null: no identity found
```

**Comment by renep** [comment]
Am I right that you have replaced the reale project name and app name in the output with {PROJECT_NAME} and {APP_NAME}. (Otherwise is is strange)

The Problem I think is 
```--sign null```
The signing identity should be displayed here and not null.

The signing identity is normally automatically taken from from the keychain that is created by the build. Here the certificate is inserted that you specify with the `certificateURI` param. Can you check the keychain on the build server if it contains the proper identity with:
```
security find-identity -v -p codesigning /Users/Shared/Jenkins/Home/workspace/{PROJECT_NAME}/build/codesign/gradle-1459858870792.keychain
```

**Comment by WearingStorm** [comment]
Yes, you are correct, I replaced the reale project names.

Thats what I believe is the problem to, but not sure how to fix it. If I understood the plugin correctly it should make a keychain and add the proper identities from the certificate. I works fine on our developer macs, but not the Jenkins server

When I ran _security find-identity -v -p code signing_ on the keychain I got:
`0 valid identities found.`

**Comment by renep** [comment]
Yes the plugin creates a keychain at the build process and added the certificate to make sure that the correct certificate is used. If the output says that no identity is found, then the keychain is not created properly. You can run gradle with `--debug` and see all the commands that the plugin executes. Search for the `security` commands because that are the ones the creates the keychain and add the certificate.
I would guess that the certificate is not found or cannot be read, therefor the keychain is not created properly.

The thing that it works on the developer machine is, that if the gradle keychain does not contain the proper certificate, the other keychains are search, which also includes the login keychain. And on developer machines it is very likely that the login keychain contains a certificate that is valid for signing.

**Comment by WearingStorm** [comment]
After reading thru the log it still doesn't make any sense why no identity is found, because just a few lines before it says 2 identities added. Maybe you can se something I missed, attached the log.

Yes, but when I testen on the developer machines we first deleted all the certificates. Then when we ran the gradle script, they got added back. 

[Jenkins log.txt](https://github.com/openbakery/gradle-xcodePlugin/files/205921/Jenkins.log.txt)

**Comment by renep** [comment]
I can verify this now. It looks like this is an issue with the latest OS X or Xcode update.

As workaround for now you can set the identity manually with
```
signing {
        identity = "iPhone Distribution ..."
}
```

I will fix this in the next version.

**Comment by renep** [comment]
Nope, this is not a Bug.

The problem is that the Apple WWDR is expired!
See: https://developer.apple.com/support/certificates/expiration/

You need to delete the expired Apple WWDR Certificate from your keychain and then add the new one that you get from here:
https://developer.apple.com/certificationauthority/AppleWWDRCA.cer

In the Keychain Accress you need to show the expired certificates with: View -> Show Expired Certificates

**Comment by WearingStorm** [comment]
Yes! That fixed the issue.

The slave already had the new certificate, but for some reason it used the old one.
After deleting the WWDR certificate it worked fine.

Thank you very much!
