### ISSUE TITLE
Publish xcode-plugin to jcenter/mavenCentral

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#261]
Instead using the "plugins" and instead of having to do this:
```
buildscript {
    repositories {
        jcenter()
        maven { url 'http://repository.openbakery.org/' }
    }

    dependencies {
        classpath 'org.openbakery:xcode-plugin:0.13.0'
    }
}
```

It would be nice to be able to download the plugin via jcenter or mavenCentral:
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.openbakery:xcode-plugin:0.13.0'
    }
}
```

**Comment by renep** [comment]
You can use this:
```
plugins {
  id "org.openbakery.xcode-plugin" version "0.13.0"
}
```

Which is the best and shortest option, because the plugin is also hosted on https://plugins.gradle.org

The longer Version of the `http://repository.openbakery.org/`is for my internal testing. On my CI Server the example projects are always tested with the lastest development version, and to achive this, my internal DNS Server points to an internal server with the lastest dev version.

**Comment by jaredsburrows** [comment]
@renep I know but not all plugins are on the official gradle repository. That is why I made this issue.

What is the point of doing 

```
plugins {
  id "org.openbakery.xcode-plugin" version "0.13.0"
}
```
and then for all other plugins:

```
buildscript {
  repositories {
  ...
  }
  dependencies {
  ...
  }
}
```

**Comment by renep** [comment]
I think that the goal of the gradle team is to get all the plugins to https://plugins.gradle.org what I think is a good idea to have a central place. An then the 
```
buildscript {
  repositories {
  ...
  }
  dependencies {
  ...
  }
}
```
will be obsulete.

**Comment by jaredsburrows** [comment]
@renep Yeah but how long will that take :/.
