### ISSUE TITLE
Print: Entry, ":com.apple.developer.ubiquity-kvstore-identifier", Does Not Exist

### ISSUE THREAD

**Issue by tw-safad** [openbakery/gradle-xcodePlugin#283]
Hi ,

Im trying to run "gradle package/GradleTest/AdHoc" task , Its throwing icloud error saying 

**console output**
Tail of output:
  Print: Entry, ":com.apple.developer.ubiquity-kvstore-identifier", Does Not Exist
  null: no identity found 

********************

Do i need to change anything on build,gradle??

**Comment by renep** [comment]
The `Print: Entry, ":com.apple.developer.ubiquity-kvstore-identifier", Does Not Exist` is not the problem here, because during the packaging the provisioning profile is analyzed, and the message only indicates that the provisioning profile does not have an entitlement with this value.

The real problem is the message `no identity found`.
You have to specify a p12 file containing the certificate with want to use for signing. During the build a keychain is created and this p12 in imported. The imported certificate is then used for codesigning, and here proper identity is read from the keychain.

You have the message that the no identity is found. Therefor your sign settings in the build.gradle are not correct. You need the a proper certificate that you normally can export from your login keychain. Then you also need a proper mobile provisioning profile that you have to create at the apple member center.
See also: https://github.com/openbakery/gradle-xcodePlugin/blob/master/Documentation/Parameters.md#sign-settings

**Comment by tw-safad** [comment]
Thanks .
