### ISSUE TITLE
Keychain access and deeplink capabilities are broken

### ISSUE THREAD

**Issue by semdangelo** [openbakery/gradle-xcodePlugin#292]
We are using the plugin for an app that uses both deep link and keychain access. Maybe we are the first user with this needs? 

Our testers reports that from gradle-xcode build introduction the app stopped working properly in all functionalities that involves one of the two capabilities.
Switching back to dear-old build from xcode,  all issues are gone.

Looking inside .app packages we can't see what's wrong, packages seems to be identical.

We have founded a workaround that consists in skip the package task and replace it dear old xcode archiver GUI .ipa creation. We are now trying to automate this.

**Comment by renep** [comment]
The question is that the problem ist. The deep linking issue could be releated to #286

The keychain sharing should work, because I have an app myself that has extension where a shared keychain is used.

To investigate this it would be nice if you could compare the entitlement that is used when signing using xcode and then with the plugin.
To get the entitlement, you need to extract the created ipa and then run the following command for your app:
```codesign -d --entitlements - Payload/MyApp.app```

**Comment by semdangelo** [comment]
Same result as in #286  
We are anyway working on an alternative way to export the .ipa, something like:

`xcodebuild -exportArchive -archivePath $PWD/build/myApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build`

The exportOptions.plist is a particular plist, there we may set all values that xcode>7 let us fill with it's GUI.

**Comment by renep** [comment]
There is now an option in 0.14.2 that the `xcodebuild -exportArchive` is used for creating the archive

**Comment by bamx23** [comment]
I've tried this option (`useXcodebuildArchive`) and it creates app in `build/dst/Applications/` directory, but `package` task looks for `.xcarchive` in `build/archive` directory. What do I do wrong?

**Comment by bamx23** [comment]
@renep could you please check if `useXcodebuildArchive` works in the latest release?

**Comment by renep** [comment]
see #311
