### ISSUE TITLE
Gradle test task failing following update to Xcode 8

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#296]
I have an iOS Framework project that is composed of the main Framework target as well as a static library target. I've been running the `gradle test` task on this project with Xcode 7 installed and the tests in the test target having been running as expected. Following my update of Xcode yesterday to the latest version (8), the tests run fine within Xcode but fail when run via the `gradle test` task.

I see that the `gradle test` task does manage to launch the simulator but the task fails subsequently with a linking error as follows:

```
ERROR - Linking: Build/sym/Debug-iphonesimulator/MySDK.framework/MySDK
Testing failed:
"_AbstractTicketDecoder_initialize", referenced from:
"_AccountConverters_initialize", referenced from:
...
```

The classes that it's complaining of are those that reside in the static library target.

Is anyone else having problems running their tests via the Gradle plugin?

**Comment by renep** [comment]
I have also problems with one project that the tests do not execute.

I have the following error in the Session-Tests log:
`2016-09-15 12:33:07.921 xcodebuild[94655:387847] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}`

(You find the Sesson-Test log the the Derived Data directory when you view the ouput in the Console.app)

Can you confirm that you have the same issue?

**Comment by adil-hussain-84** [comment]
Hey @renep, this is what I see in the log file in my Derived Data directory:

    ...
    12:49:09.206 xcodebuild[14819:145675] Waiting for test process to launch.
    12:49:22.565 xcodebuild[14819:145675] Test operation failure: Test operation was canceled.
    12:49:22.565 xcodebuild[14819:145675] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1

I suspect the test operation was cancelled for me because of the linking error as pasted in my question earlier but I'm not certain. I'll try running my tests from the command line using the `xcodebuild test ...` command instead of the Gradle task. Will let you know if that reports the same linking error or not.

**Comment by adil-hussain-84** [comment]
Just tried running my tests with this command...

    xcodebuild test -workspace MySDK.xcworkspace -scheme MySDK -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'

... and the tests ran successfully. Not sure what's going wrong with the Gradle plugin?

**Comment by renep** [comment]
I'm wondering...
You say you use Xcode8, but you run the tests with the iOS 9 simulator.

**Comment by adil-hussain-84** [comment]
Hey @renep, sorry, I should have said: I tried running the tests via the Gradle plugin against the iOS 10.0 Simulator also and got the same linking error.

The reason I ran the `xcodebuild test ...` command against the iOS 9.3 Simulator is because my tests are failing when run against the iOS 10.0 Simulator but that's for reasons independent of the Gradle plugin.

**Comment by renep** [comment]
Have you tried the 0.14.2-develop version?

**Comment by hennykat** [comment]
I also have an issue with my test task failing with xcode 8.  I get the following when attempting to run my tests:
:xcodetest
Testing failed:
        Command failed due to signal: Segmentation fault: 11

These tests do run correctly in xcode8 using the same simulators.

How do we use the 0.14.2-develop version?  I have tried classpath "org.openbakery:xcode-plugin:0.14.0.develop.+" and classpath "org.openbakery:xcode-plugin:0.14.2.develop.+" and neither have made a difference for me.

**Comment by renep** [comment]
@hennykat can you run the `gradle` command with `-debug` and post (or mail me) the last part of the log output, so that I can see what is wrong.

**Comment by hennykat** [comment]
Command: gradle test -debug
Simulator: iPhone 6s iOS 10
Last part of debug output:
09:56:48.073 [INFO] [org.openbakery.CommandRunner] <unknown>:0: error: unable to execute command: Segmentation fault: 11
09:56:48.073 [INFO] [org.openbakery.CommandRunner] <unknown>:0: error: compile command failed due to signal (use -v to see invocation)
09:56:48.073 [INFO] [org.openbakery.CommandRunner] === BUILD TARGET SwiftKeychainWrapper OF PROJECT Pods WITH CONFIGURATION dev ===
09:56:48.073 [INFO] [org.openbakery.CommandRunner] Check dependencies
09:56:48.073 [INFO] [org.openbakery.CommandRunner] 
09:56:48.074 [INFO] [org.openbakery.CommandRunner] Ld /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/x86_64/SwiftKeychainWrapper normal x86_64
09:56:48.074 [INFO] [org.openbakery.CommandRunner]     cd /Users/emilyhennessy/workspace-swift/ios/Pods
09:56:48.074 [INFO] [org.openbakery.CommandRunner]     export IPHONEOS_DEPLOYMENT_TARGET=8.0
09:56:48.074 [INFO] [org.openbakery.CommandRunner]     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/emilyhennessy/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
09:56:48.074 [INFO] [org.openbakery.CommandRunner]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -L/Users/emilyhennessy/workspace-swift/ios/build/sym/dev-iphonesimulator/SwiftKeychainWrapper -F/Users/emilyhennessy/workspace-swift/ios/build/sym/dev-iphonesimulator/SwiftKeychainWrapper -filelist /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/x86_64/SwiftKeychainWrapper.LinkFileList -install_name @rpath/SwiftKeychainWrapper.framework/SwiftKeychainWrapper -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -object_path_lto -Xlinker /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/x86_64/SwiftKeychainWrapper_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -fprofile-instr-generate -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/x86_64/SwiftKeychainWrapper.swiftmodule -framework Foundation -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/x86_64/SwiftKeychainWrapper_dependency_info.dat -o /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/x86_64/SwiftKeychainWrapper
09:56:48.074 [INFO] [org.openbakery.CommandRunner] 
09:56:48.075 [INFO] [org.openbakery.CommandRunner] Ld /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/i386/SwiftKeychainWrapper normal i386
09:56:48.075 [INFO] [org.openbakery.CommandRunner]     cd /Users/emilyhennessy/workspace-swift/ios/Pods
09:56:48.075 [INFO] [org.openbakery.CommandRunner]     export IPHONEOS_DEPLOYMENT_TARGET=8.0
09:56:48.075 [INFO] [org.openbakery.CommandRunner]     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/emilyhennessy/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
09:56:48.075 [INFO] [org.openbakery.CommandRunner]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -L/Users/emilyhennessy/workspace-swift/ios/build/sym/dev-iphonesimulator/SwiftKeychainWrapper -F/Users/emilyhennessy/workspace-swift/ios/build/sym/dev-iphonesimulator/SwiftKeychainWrapper -filelist /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/i386/SwiftKeychainWrapper.LinkFileList -install_name @rpath/SwiftKeychainWrapper.framework/SwiftKeychainWrapper -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -object_path_lto -Xlinker /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/i386/SwiftKeychainWrapper_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -fprofile-instr-generate -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/i386/SwiftKeychainWrapper.swiftmodule -framework Foundation -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/i386/SwiftKeychainWrapper_dependency_info.dat -o /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/i386/SwiftKeychainWrapper
09:56:48.075 [INFO] [org.openbakery.CommandRunner] 
09:56:48.076 [INFO] [org.openbakery.CommandRunner] CreateUniversalBinary /Users/emilyhennessy/workspace-swift/ios/build/sym/dev-iphonesimulator/SwiftKeychainWrapper/SwiftKeychainWrapper.framework/SwiftKeychainWrapper normal i386\ x86_64
09:56:48.076 [INFO] [org.openbakery.CommandRunner]     cd /Users/emilyhennessy/workspace-swift/ios/Pods
09:56:48.076 [INFO] [org.openbakery.CommandRunner]     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/emilyhennessy/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
09:56:48.076 [INFO] [org.openbakery.CommandRunner]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/i386/SwiftKeychainWrapper /Users/emilyhennessy/workspace-swift/ios/build/obj/Pods.build/dev-iphonesimulator/SwiftKeychainWrapper.build/Objects-normal/x86_64/SwiftKeychainWrapper -output /Users/emilyhennessy/workspace-swift/ios/build/sym/dev-iphonesimulator/SwiftKeychainWrapper/SwiftKeychainWrapper.framework/SwiftKeychainWrapper
09:56:48.176 [INFO] [org.openbakery.CommandRunner] 
09:56:48.254 [INFO] [org.openbakery.CommandRunner] 2016-09-26 09:56:48.250 xcodebuild[8018:54631] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/emilyhennessy/workspace-swift/ios/build/derivedData/Logs/Test/D4EC1CFF-4EE4-438E-8883-5B9B39F10FAC/Session-DeviceConXUITests-2016-09-26_095611-DHt05S.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/emilyhennessy/workspace-swift/ios/build/derivedData/Logs/Test/D4EC1CFF-4EE4-438E-8883-5B9B39F10FAC/Session-DeviceConXUITests-2016-09-26_095611-DHt05S.log}
09:56:48.255 [INFO] [org.openbakery.CommandRunner] 2016-09-26 09:56:48.251 xcodebuild[8018:54631] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/emilyhennessy/workspace-swift/ios/build/derivedData/Logs/Test/D4EC1CFF-4EE4-438E-8883-5B9B39F10FAC/Session-DeviceConXTests-2016-09-26_095611-cCisl2.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/emilyhennessy/workspace-swift/ios/build/derivedData/Logs/Test/D4EC1CFF-4EE4-438E-8883-5B9B39F10FAC/Session-DeviceConXTests-2016-09-26_095611-cCisl2.log}
09:56:48.274 [INFO] [org.openbakery.CommandRunner] 
09:56:48.274 [INFO] [org.openbakery.CommandRunner] Testing failed:
09:56:48.275 [INFO] [org.openbakery.CommandRunner]      Command failed due to signal: Segmentation fault: 11
09:56:48.276 [INFO] [org.openbakery.CommandRunner] ** TEST FAILED **
09:56:48.276 [DEBUG] [org.openbakery.output.TestBuildOutputAppender] printFailureOutput
09:56:48.277 [LIFECYCLE] [org.openbakery.XcodeBuildTask] Testing failed:
09:56:48.278 [LIFECYCLE] [org.openbakery.XcodeBuildTask]        Command failed due to signal: Segmentation fault: 11
09:56:48.278 [LIFECYCLE] [org.openbakery.XcodeBuildTask] 0 tests completed
09:56:48.278 [INFO] [org.openbakery.CommandRunner] 
09:56:48.278 [INFO] [org.openbakery.CommandRunner] 
09:56:48.278 [INFO] [org.openbakery.CommandRunner] The following build commands failed:
09:56:48.279 [INFO] [org.openbakery.CommandRunner]      CompileSwift normal x86_64 /Users/emilyhennessy/workspace-swift/ios/Pods/CryptoSwift/Sources/CryptoSwift/Generics.swift
09:56:48.279 [INFO] [org.openbakery.CommandRunner]      CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
09:56:48.279 [INFO] [org.openbakery.CommandRunner] (2 failures)
09:56:48.297 [DEBUG] [org.openbakery.CommandRunner] Exit Code: 65
09:56:48.298 [DEBUG] [org.gradle.api.Task] store to test-result.xml
09:56:48.298 [LIFECYCLE] [org.gradle.api.Task] Test Results generated in 0:00:00.001

09:56:48.298 [LIFECYCLE] [org.gradle.api.Task] All 0 tests were successful
09:56:48.299 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':xcodetest'
09:56:48.299 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :xcodetest FAILED
09:56:48.299 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :xcodetest (Thread[Daemon worker Thread 5,5,main]) completed. Took 38.93 secs.
09:56:48.299 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.4 completed (0 in use)
09:56:48.299 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 5,5,main]] finished, busy: 39.099 secs, idle: 0.002 secs
09:56:48.300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:56:48.300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:56:48.300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:56:48.300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
09:56:48.300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':xcodetest'.
09:56:48.300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.Exception: Error attempting to run the unit tests!
09:56:48.301 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:56:48.301 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
09:56:48.301 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
09:56:48.301 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
09:56:48.301 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
09:56:48.301 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
09:56:48.301 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 40.783 secs

**Comment by hennykat** [comment]
command: gradle build -debug
simulator: iPhone 6s 10.1
log output:
`15:38:15.968 [INFO] [org.openbakery.CommandRunner] 2016-09-26 15:38:15.968 xcodebuild[30367:187800] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at workspace-swift/ios/build/derivedData/Logs/Test/C20C08F3-68B6-4C46-B4C3-6B9044656EEE/Session-Tests-2016-09-26_153658-ph7U8O.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /workspace-swift/ios/build/derivedData/Logs/Test/C20C08F3-68B6-4C46-B4C3-6B9044656EEE/Session-Tests-2016-09-26_153658-ph7U8O.log}
15:38:15.992 [INFO] [org.openbakery.CommandRunner] 
15:38:15.992 [INFO] [org.openbakery.CommandRunner] Testing failed:
15:38:15.992 [INFO] [org.openbakery.CommandRunner]      Command failed due to signal: Segmentation fault: 11
15:38:15.993 [INFO] [org.openbakery.CommandRunner] ** TEST FAILED **
15:38:15.993 [DEBUG] [org.openbakery.output.TestBuildOutputAppender] printFailureOutput
15:38:15.996 [LIFECYCLE] [org.openbakery.XcodeBuildTask] Testing failed:
15:38:15.996 [LIFECYCLE] [org.openbakery.XcodeBuildTask]        Command failed due to signal: Segmentation fault: 11
15:38:15.997 [LIFECYCLE] [org.openbakery.XcodeBuildTask] 0 tests completed
15:38:15.997 [INFO] [org.openbakery.CommandRunner] 
15:38:15.998 [INFO] [org.openbakery.CommandRunner] 
15:38:15.998 [INFO] [org.openbakery.CommandRunner] The following build commands failed:
15:38:15.998 [INFO] [org.openbakery.CommandRunner]      CompileSwift normal i386 /workspace-swift/ios/Pods/CryptoSwift/Sources/CryptoSwift/Generics.swift
15:38:15.998 [INFO] [org.openbakery.CommandRunner]      CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
15:38:15.998 [INFO] [org.openbakery.CommandRunner] (2 failures)
15:38:16.016 [DEBUG] [org.openbakery.CommandRunner] Exit Code: 65
15:38:16.017 [DEBUG] [org.gradle.api.Task] store to test-result.xml
15:38:16.018 [LIFECYCLE] [org.gradle.api.Task] Test Results generated in 0:00:00.001

15:38:16.018 [LIFECYCLE] [org.gradle.api.Task] All 0 tests were successful
15:38:16.018 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':xcodetest'
15:38:16.018 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :xcodetest FAILED
15:38:16.019 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :xcodetest (Thread[Daemon worker Thread 3,5,main]) completed. Took 1 mins 19.468 secs.
15:38:16.019 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.4 completed (0 in use)
15:38:16.019 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 3,5,main]] finished, busy: 1 mins 19.618 secs, idle: 0.002 secs
15:38:16.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:38:16.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:38:16.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:38:16.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:38:16.020 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':xcodetest'.
15:38:16.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.Exception: Error attempting to run the unit tests!
15:38:16.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:38:16.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
15:38:16.021 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
15:38:16.021 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
15:38:16.021 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
15:38:16.021 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
15:38:16.021 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 1 mins 21.133 secs`

**Comment by renep** [comment]
Looks like that the simulator can be launched or crashes.
Can you try to shut down the simulator first and then run a "gradle simCreate" so that all the simualtors are recreated and try the build again.

**Comment by hennykat** [comment]
I get the same results after running 'gradle simCreate'.  I have also tried on a 9.3 simulator and a 10.1 beta simulator with the same results.

**Comment by renep** [comment]
And using Xcode 8 compiling and running the unit tests works?

What does the log file say that in `derivedData/Logs/Test...`

**Comment by hennykat** [comment]
I have since upgraded to xcode 8.1 beta and I have cocoapods version 1.1.0.rc.2.  Compiling and running unit tests works with 8.1 and it previously worked with 8.  I am also able to successfully run tests using fastlane with the command 'fastlane test'.  I can build with gradle, but I cannot test with gradle.

My derivedData/Logs/Test contains:

```
10:19:48.587 xcodebuild[1545:10916] Beginning test session Tests-750B3B03-AAAB-4D2C-BC4F-77C031C0E4AA at 2016-09-27 10:19:48.585 with Xcode 8T29o on target <DVTiPhoneSimulator: 0x7fc73bf08860> {
		SimDevice: SimDevice : iPhone 6s (6A2B5856-1A2D-4808-9E1B-17D0EC5BD78B) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 10.1 (14B54) - com.apple.CoreSimulator.SimRuntime.iOS-10-1 }
} (10.1 (14B54))
10:19:48.587 xcodebuild[1545:10916] 	/Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild
-scheme
dev
-workspace
AppName.xcworkspace
-configuration
dev
CODE_SIGN_IDENTITY=
CODE_SIGNING_REQUIRED=NO
-destination
name=iPhone 6s
-derivedDataPath
/workspace-swift/ios/build/derivedData
DSTROOT=/workspace-swift/ios/build/dst
OBJROOT=/workspace-swift/ios/build/obj
SYMROOT=/workspace-swift/ios/build/sym
SHARED_PRECOMPS_DIR=/workspace-swift/ios/build/shared
-enableCodeCoverage
yes
test
10:19:48.587 xcodebuild[1545:10916] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
10:19:48.590 xcodebuild[1545:10916] Initializing test infrastructure.
10:19:48.590 xcodebuild[1545:10919] 6A2B5856-1A2D-4808-9E1B-17D0EC5BD78B: Registered for sim device notification, got token 4
10:19:48.590 xcodebuild[1545:10919] 6A2B5856-1A2D-4808-9E1B-17D0EC5BD78B: Unregistering for sim device notification with token 4
10:19:48.590 xcodebuild[1545:10919] Sim iPhone 6s is booted (state = 3)
10:19:48.590 xcodebuild[1545:10919] Calling -[SimDevice getenv:error:] for TESTMANAGERD_SIM_SOCK
10:19:48.591 xcodebuild[1545:10919] Returning /private/tmp/com.apple.launchd.tMf31lx3td/com.apple.testmanagerd.unix-domain.socket for TESTMANAGERD_SIM_SOCK
10:19:48.591 xcodebuild[1545:10919] Sim iPhone 6s has testmanagerd socket at /private/tmp/com.apple.launchd.tMf31lx3td/com.apple.testmanagerd.unix-domain.socket
10:19:48.591 xcodebuild[1545:10919] Connected socket 33 to testmanagerd for Sim iPhone 6s
10:19:48.592 xcodebuild[1545:10919] Creating the test bundle connection.
10:19:48.592 xcodebuild[1545:10919] Listening for proxy connection request from the test bundle (all platforms)
10:19:48.592 xcodebuild[1545:10919] Resuming the connection.
10:19:48.593 xcodebuild[1545:10919] Test connection requires daemon assistance.
10:19:48.598 xcodebuild[1545:10916] Received Ready from iOSSimulator
10:19:48.598 xcodebuild[1545:10916] Sending notification: NSConcreteNotification 0x7fc73c30f7d0 {name = com.apple.iphonesimulator.startSession; userInfo = {
    deviceUDID = "6A2B5856-1A2D-4808-9E1B-17D0EC5BD78B";
}}
10:19:48.783 xcodebuild[1545:10916] Starting test session with ID <__NSConcreteUUID 0x7fc73c1f6ce0> 750B3B03-AAAB-4D2C-BC4F-77C031C0E4AA
10:19:48.783 xcodebuild[1545:10916] Checking test manager availability..., will wait up to 120s
10:19:50.090 xcodebuild[1545:10970] testmanagerd handled session request.
10:19:50.091 xcodebuild[1545:10916] Waiting for test process to launch.
10:20:14.292 xcodebuild[1545:10916] Test operation failure: Test operation was canceled.
10:20:14.292 xcodebuild[1545:10916] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1
```

**Comment by adil-hussain-84** [comment]
Hi @renep, I just tried using the current development version of the plugin but unfortunately I'm seeing the same error message as describe earlier in this thread.

**Comment by renep** [comment]
Does this issue also occur when you create a new project?

If not can you create example project that has this problem.

My problem is that I cannot reproduce this issue, therefor it is hard to guess what the problem is.

**Comment by adil-hussain-84** [comment]
@renep: Sure, I'll make a new project that demonstrates the problem. Watch this space.

**Comment by wujood** [comment]
I'm having the same issue. Last week everything worked fine. Now that i have Unit-Tests in Swift instead of obj-C the test won't run. Any update?

**Comment by renep** [comment]
As I said, I cannot reproduce this issue. If someone provide an example project where I can reproduce this issue, I can work on it.

**Comment by adil-hussain-84** [comment]
Apologies for the delay in putting together a project that demonstrates this error. It's on my todo list.

**Comment by CodeStage** [comment]
FYI: I had the following error when running a test target on Jenkins, but not when running it directly in Xcode. As it turns out, you need to copy your frameworks in a copy files phase for test targets...

xcodebuild[75962:9097252] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

**Comment by adil-hussain-84** [comment]
@CodeStage: good to hear you got it working! What values did you put in for "Destination", "Subpath" etc in the "Copy Files" Build Phases setting that you added?

I've attached a screenshot of my project structure (see below). As you can see, my test target links to the "ShardCode" and "TestContracts" static library targets by by means of the "Link Binary With Libraries" Build Phase. And my test target links to the "JustRideSDK" target by means of the "Compile Sources" Build Phase. The tests run and pass when run in Xcode. I get linker errors however when running the tests by means of the Xcode Gradle plugin.

(I am yet to compose a small example of the problem. Watch this space!)

![screen shot xcode project](https://cloud.githubusercontent.com/assets/17025131/22290633/e7fb6c68-e2f9-11e6-8047-ca261ef2d551.png)

**Comment by CodeStage** [comment]
Destination: Frameworks
Rest: blank

I had to add the **dynamic frameworks** (e.g. Swift frameworks) in a copy files phase.

You don't need to copy static libraries for test targets AFAIK, because they are already linked to your app. So you might have another issue there...

**Comment by adil-hussain-84** [comment]
Good news: I've just tried this on Xcode 9.0 with the latest development version of this plugin and it appears to be working again.
