### ISSUE TITLE
Close the simulator at the end of tests

### ISSUE THREAD

**Issue by la-urre** [openbakery/gradle-xcodePlugin#323]
The simulator is closed at the beginning of tests, but I would like it to be closed at the end too. I don't know if this would be a complicated thing to do in the plugin, but I managed to do it in my script. Here:

```
task killSimulator(type: org.openbakery.simulators.SimulatorKillTask)

// make sure we always kill the simulator whenever the tests are successful or failed
xcodetest.finalizedBy killSimulator
```

Maybe this could help to implement the feature ? Or at least people that want to have it in their script.

**Comment by phatblat** [comment]
This would help with issues where builds using different versions of Xcode can step on each others' toes because they launch different versions of the CoreSimulatorService. When a build with Xcode 9 launches the simulator (and service), the Xcode 8.3 is invoked you get this lovely error:

>    - ERROR | [iOS] unknown: Encountered an unknown error (743: unexpected token at '2017-09-22 13:16:21.767 simctl[23337:980611] CoreSimulator detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Applications/Xcode83.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework) and version (375.21) does not match existing job path (/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc) and version (494.13.6).  Attempting to remove the stale service in order to add the expected version.

Killing the simulator and CoreSimulatorService between builds would prevent this, however if another project was currently running tests in the simulator, killing it would break that build. So, if this were to be implemented, there should be a way to disable this behavior on a CI system that is running multiple builds concurrently.
