### ISSUE TITLE
Random error: 0 tests executed

### ISSUE THREAD

**Issue by la-urre** [openbakery/gradle-xcodePlugin#337]
I sometimes get an error on the CI server.

I have 1000+ unit tests but sometimes the automated build fails, because of the following error:

> 0 tests completed
> All 0 tests were successful
> :myProject:xcodetest FAILED
> :myProject:killSimulator
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':src:SDKGeneric:ios:tests:BridgeiOSTest:xcodetest'.
> > java.lang.Exception: Error attempting to run the unit tests!

The tests are runned on the iPhone 7 Plus simulator.

I noticed this problem might be related to the CI server running some tasks concurrently. It seems to happen when several builds are triggered on different development branches. I know the iPhone simulator is always a single instance, so killing the simulator from one build while executing the tests from another one may cause problems.

What could I do to prevent this error ? Can something be done in the plugin to prevent concurrent tests execution ?

**Comment by renep** [comment]
No, I do not intend to add some concurrent protection in the plugin, because I think this is not something the plugin should do to block other builds.
One thing that could be an option is that multiple simulators can be executed at one box. There is a project that does this (https://github.com/linkedin/bluepill), and this could be in option to include in the plugin. But this is not on my todo list for the near future, there is other stuff I think is more important.

For your current problem there is something that you can try that could help. With version 0.14.5 of the gxp there is an option that you can create a build with all the unit tests. When you run `gradle xcodebuildForTest` you will get a package of your app with all the unit tests in `build/for-testing`. You can take this package and copy in to another box (if you want or do this on the same box) and run `build xcodetestrun` and all the unit tests in the package are executed.
The benefit of this, is that the long taking compile task is separated from the actual unit test run. So you can run the compile task in parallel but the unit test execution only in a single instance.

What you can also do is to execute the unit tests on real devices, and then you can have multiple devices connected to your build node, so you can also run tests in parallel.

**Comment by laurre** [comment]
Thanks for your feedback. 

Past night I once again had the problem, but this time, no concurrent execution. I browsed the available logs. The only meaningful logs I can extract are: 

> 21:22:39.314 xcodebuild[8574:26086] Starting test session with ID 4DB220DE-C620-480C-A41E-77BFA9EEAF2F
> 21:22:39.314 xcodebuild[8574:26086] Checking test manager availability..., will wait up to 120s
> 21:24:23.207 xcodebuild[8574:26356] Closing socket 31 to testmanagerd for Sim iPhone 7 Plus
> 21:24:23.337 xcodebuild[8574:26215] Error from testmanagerd: The operation couldnâ€™t be completed. (DTXProxyChannel error 1.) ((null))
> 21:24:23.337 xcodebuild[8574:26086] Test operation failure: The operation couldnâ€™t be completed. (DTXProxyChannel error 1.)
> 21:24:23.337 xcodebuild[8574:26086] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "The operation couldnâ€™t be completed. (DTXProxyChannel error 1.)" UserInfo={NSLocalizedDescription=The operation couldnâ€™t be completed. (DTXProxyChannel error 1.)} didCancel: 1

It seems to be a problem with the emulator launching. Is the testmanagerd off ? I don't think it is related with the gradle plugin, but maybe you have some details about that error ?

**Comment by laurre** [comment]
Maybe related to this post ? http://stackoverflow.com/questions/37922146/xctests-failing-on-physical-device-canceling-tests-due-to-timeout/40790171#40790171

**Comment by renep** [comment]
What do you execute? `gradle test`? or do you use the new `gradle xcodebuildForTest` and `gradle xcodetestrun`?

**Comment by laurre** [comment]
I execute `gradle xcodetest`

**Comment by renep** [comment]
Have you tried to clean the simulators first or recreate them using `gradle simClean` or `gradle simCreate` to have a clean state.

**Comment by renep** [comment]
I do that always
