### ISSUE TITLE
.ipa file size increase and unable to install this ipa on device

### ISSUE THREAD

**Issue by YogeshBharate** [openbakery/gradle-xcodePlugin#353]
Hi,

I am using gradle-xcode plugin for creating the .ipa for my project, but its observed that the file size of ipa is increase to 77 MB instead of 23MB. When I create the ipa file using xcode its size is 23 MB, and when i create it using gradle-xcode plugin its size increase to 77MB and also which is unable to installed on device.

When I extract .ipa file i found that it contents SwiftSupport extra directory, How should we avoid this to reduce the ipa file size ? Is it necessary for folder ?

**Comment by renep** [comment]
The SwiftSupport folder is needed for AdHoc builds. At least this was the case a year ago. Maybe this has changed now, and should be tested again.
This SwiftSupport folder is not added for AppStore builds. To determine if it is a AppStore build or a AdHoc build, the provisioning profile if investigated if `ProvisionedDevices` are available. If so it is an AdHoc Build.

Can you plugin in the device on your machine and have a look at the syslog when installing the IPA on the device, so that you can maybe see what the problem is, why the IPA cannot be installed.
