### ISSUE TITLE
xcodetest task produces empty test-results.xml file with Xcode 10.0

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#398]
I've just upgraded my Xcode installation from 9.4.1 to 10.0 and I'm seeing that the `xcodetest` task is able to run the tests but it's no longer able to parse the output produced by the tests in order to produce a `test-results.xml` file. The file is produced but its contents are as follows:

    <testsuites />

On inspection of the `derivedData/Logs/Test` folder I can see that the two versions of Xcode name and place the `TestSummaries.plist` file differently. On Xcode 9.4.1 the file takes the format `derivedData/Logs/Test/<device identifier>_TestSummaries.plist` and on Xcode 10.0 it takes the format `derivedData/Logs/Test/Test-<project name>-<date>-<time>.xcresult/TestSummaries.plist`.

I have tried with the latest development version of the plugin (`0.15.3.developer.+`) but the output is the same as the latest stable release (`0.15.3`). I can provide further details if required.

**Comment by renep** [comment]
Yes I found that out already and for my projects it is annoying to find out what unit tests failed.

I think i will parse the `Test/Logs/LogStoreManifest.plist` because here the TestSummaries.plist list listed.

I cannot say when I have a fix for this, because I'm quite busy the next few days, but it will be the next thing on my list, because I will need this for my projects.
