### ISSUE TITLE
'xcodebuild' is not up-to-date because:   Task has not declared any outputs despite executing actions

### ISSUE THREAD

**Issue by wizofaus** [openbakery/gradle-xcodePlugin#404]
The xcodebuild task generated by the plugin doesn't appear to analyse the workspace/project files to determine the inputs and outputs.  If xcodebuild itself did a good job of this and exited quickly when there was no work to do this wouldn't be a major issue but it's rubbish, often taking several minutes to rebuild things quite unnecessarily.
Even if it were just an option, the ability to use gradles' much much faster dependency checking would be a huge bonus.

**Comment by renep** [comment]
The xcodebuild task is only an adapter to the `xcodebuild` commandline tool. Therefor all the dependency checking is done by the xcodebuild commandline tool.
Making this plugin smarter so that not the xcodebuild tool is used for compiling the files and handling all the dependencies would be nice, but I don't think this is going to happen in the foreseeable future.
This plugin is only a side project for me and there are lots of things I would like to add or make better. But I have mostly only time to update and add things I need for the iOS projects I'm working and where I use this plugin.
