### ISSUE TITLE
Could not generate a proxy class for class org.openbakery.carthage.CarthageUpdateTask

### ISSUE THREAD

**Issue by mukhasir** [openbakery/gradle-xcodePlugin#408]
Hello Team, 
I am using the latest plugin version 0.15.4 in my gradle file. I am using 2.14 as my gradle version then it gives me the following error. Can you please help me on fixing this. 

This has been working good for 0.15.1.develop.+ version. But for new version 0.15.4 and 0.15.4.develop.+ it is not working.  Need help on this. 

*** What went wrong:
A problem occurred evaluating root project 'XXXX'.
> Failed to apply plugin [id 'org.openbakery.xcode-plugin']
   > Could not generate a proxy class for class org.openbakery.carthage.CarthageUpdateTask.**

Thanks in Advance.

**Comment by phatblat** [comment]
I get this error all the time in Gradle plugins I'm developing in Kotlin because classes are `final` by default (it's easy to set them to [`open`](https://github.com/phatblat/ShellExec/blob/master/src/main/kotlin/at.phatbl.shellexec/ShellExec.kt#L14), but I always forget). However, the [`CarthageUpdateTask`](https://github.com/openbakery/gradle-xcodePlugin/blob/4bd7593b9068928e99f9291a4b702f4e7f96aa6a/plugin/src/main/groovy/org/openbakery/carthage/CarthageUpdateTask.groovy) class is written in groovy, so it must be a different issue.

Gradle doesn't invoke custom task classes as you'd expect, but rather creates a proxy for them. The first thing I would suggest is to try using a newer version of Gradle. 2.14 is ancient and 5.2.1 is the current version.

The issue might also be related to the version of Java that you are using. Which JDK were you using when you tried this?

**Comment by mukhasir** [comment]
@phatblat The Java Version that i am using is 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

I have other dependent services which would require 2.14 Gradle version. But I could try with higher version. It would be good if i can get this running with 2.14 Gradle version.

**Comment by renep** [comment]
With the latest 0.15.4 I have added kotlin code. Kotlin support was added in gradle 3.0. So this could be your problem.
So I would recommend to update your gradle version. The best option for this is to use the gradle wrapper so that gradle is bootstrapped with the project: https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by mukhasir** [comment]
Thank you for the update @renep . I have tried all 3.x version but those were still giving same issue. Latest gradle version that was able to run with warnings was Gradle 4.1

Can we get backward compatibility of using older version of Gradle with newer OpenBakery plugin, just curious.
