### ISSUE TITLE
infoplist-modify task fails on 10.9 Mavericks

### ISSUE THREAD

**Issue by cordsie** [openbakery/gradle-xcodePlugin#65]
I'm trying to build an in-app purchase package via the plugin on 10.9. The result is:

> Command failed to run (exit code 1): '/usr/libexec/Plistbuddy PROJECTNAME/ContentInfo.plist -c Print :CFBundleVersion'

As far as I can see, the command should be:

/usr/libexec/ContentInfo.plist -c "Print:ContentVersion"

**Comment by smuravev** [comment]
I got similar issue:

I use the follwing configuration in my build.gradle script:
  
        infoplist {
                bundleIdentifier = 'com.vipahelda.actelion.uat'
        }

I get the error in the build process:

        Execution failed for task ':infoplist-modify'.
        > Command failed to run (exit code 1): '/usr/libexec/PlistBuddy $(SRCROOT)/Actelion/Resources/Other/SScCalculator-Info.plist -c Set :CFBundleIdentifier com.vipahelda.actelion.uat'

The problem is in command line execution of:

        /usr/libexec/PlistBuddy $(SRCROOT)/Actelion/Resources/Other/SScCalculator-Info.plist -c Set :CFBundleIdentifier com.vipahelda.actelion.uat

I tried to execute this command directly in terminal window, like this:

        /usr/libexec/PlistBuddy ./Actelion/Resources/Other/SScCalculator-Info.plist -c Set :CFBundleIdentifier com.vipahelda.actelion.uat

I got the following error:

        Invalid Arguments

Then, I tried to little change command line, I placed `Set :CFBundleIdentifier com.vipahelda.actelion.uat` between "", like this:

        /usr/libexec/PlistBuddy ./Actelion/Resources/Other/SScCalculator-Info.plist -c "Set :CFBundleIdentifier com.vipahelda.actelion.uat"

In this case execution was OK (no 'Invalid Arguments' error in output).

Well, let's summary your 'xcode' gradle plugin must generate 'PlistBuddy' execution, like:

        /usr/libexec/PlistBuddy ./Actelion/Resources/Other/SScCalculator-Info.plist -c "Set :CFBundleIdentifier com.vipahelda.actelion.uat"

NOTE: `Set :CFBundleIdentifier com.vipahelda.actelion.uat` must be placed between "", otherwise 'infoplist-modify' plugin task executes failed. Please fix it in your code.

**Comment by renep** [comment]
No, the quotes are not the problem. I'm sure of that ;-)
It looks like this, but the `Set :CFBundleIdentifier com.vipahelda.actelion.uat` is one parameter that is passed into the [ProcessBuilder](http://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html)
Of course when you run the command in the terminal you have to insert the quotes.

I think the `$(SRCROOT)` is the problem. Have you tried to modify your xcode project and specify a path without the `$(SRCROOT)`?
When you create a new xcode project, then there is no `$(SRCROOT)` at the Info.plist.

(Maybe a can add support the the `$(SRCROOT)` is processed properly, but I don't know if this is worth the affort.)

If this is not an option, then you can specify the Info.plist what the parameters `xcodebuild.infoPlist` parameter.

**Comment by smuravev** [comment]
Hello,

Thank you for your quick response and for your advice to exclude `$(SRCROOT)` from path in the xcode configuration. You are right the problem was in used `$(SRCROOT)`. I also think be better if you add supporting of `$(SRCROOT)` to parse and replace it correctly in your xcode plugin (because if we work in xcode UI and if create any new tasks in xcode IDE through UI it autimatically uses `$(SRCROOT)` to point to any files / paths).

Once again, thank you for your help. Have a good day !

P.S. I hope you will add correct parsing of `$(SRCROOT)` in further version of your awesome plugin :-)
